name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare file
        run: |
          cp packages/web/.env.tmpl packages/web/.env

      - name: Install deps
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
